### ISSUE TITLE
US 1

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#1]
## US 1

As a Beanerd 
I want so see a variety of coffee I could choose from
​

## Description

<img width="357" alt="Bildschirmfoto 2023-07-26 um 22 11 22" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/7c18b64e-6d25-4a06-ab9f-fb6cd888f1f7">

​

## Acceptance Criteria

- [x] I can see every roast
- [x] Detailpage for every roast

## Tasks

- [x] Connect to MongoDB
- [x] Create a Schema "roasts"
- [x] Fetch Data from MongoDB
- [x] Display each roast
- [x] Create dynamic page for each roast
- [x] Write a test if each roast gets displayed
      ​

## Complexity

S

**Comment by AntjeWitte** [comment]
Looks okay. Maybe the next time you could write your tasks a little more detailed.
