### ISSUE TITLE
US 6

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#11]
## Add BrewMethods and Rating

As a Beanerd I want to save BrewMethods for my favorite Roasts, so I can replicate my desired taste. I also want to be able to Rate a Roast from 0 - 100. 

## Description
<img width="380" alt="Bildschirmfoto 2023-08-09 um 11 09 25" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/d107ca3f-eb44-40f6-bae5-35f6e7759bcc">

<img width="305" alt="Bildschirmfoto 2023-08-09 um 12 23 44" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/1951015e-3410-483f-9c8f-13aaa5b9f89f">
​

## Acceptance Criteria

- [x] I can enter a detailed view for every roast in my Collection 
- [x] I can save BrewMethods for each roast in my Collection
- [x] I can rate the roast
      ​

## Tasks

- [x] create DetailView 
- [x] create Form for BrewMethods
- [x] create Input for Rating
- [x] write Logic for saving a Method with the Roast in a users profile
      ​

## Complexity

M

**Comment by JudithRe** [comment]
The form etc. are not in the description, I am assuming that it will be a textfield the user can fill out? Maybe you could specify this a little bit. 

We usually put creation of the feature branc into the tasks as well (just so you don't forget). Other than that it looks good :)

**Comment by florianblaschke** [comment]
Hi! I did not put the creation of the feature branch  in the tasks so far. I think its mandatory and doesnt need to be mentioned every single time.

**Comment by Kheirah** [comment]
Some prefer a more granular list of tasks, some don't like thinking in such small steps. As far as I'm concerned you may leave the tasks as is. You know that working on branches is obligatory and you won't forget to create one. Give it a proper name and I'm happy 😆
