### ISSUE TITLE
US7 Toast Message

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#13]
## Better UX

Right now the App feels clunky when using it because of the alerts I get, when setting e.g. a favorite.
For better Control over the App I want to be notified with small toast messages and not getting an alert from the browser.
​

## Description

![Image](https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/fc64d6c2-e214-43b8-9357-044341e8d3c3)

​

## Acceptance Criteria

- [x] all Alerts are replaced by a toast-message
      ​

## Tasks

- [x] create a Toast Component
- [x] create Animation for the Component
- [x] replace all Alerts with the Toast Component 
      ​

## Complexity

M

**Comment by jonas8900** [comment]
i like your value proposition: "Right now the App feels clunky when using it because of the alerts I get, when setting e.g. a favorite.
For better Control over the App I want to be notified with small toast messages and not getting an alert from the browser." LGTM !

**Comment by migueljcpinto** [comment]
Olá Florian! 
I noticed that you have a cafe with the Portuguese name "Fazenda Matão". But, when I went to test your app, modifying that cafe, it doesn't accept the "ã" that already exist, because you don't allow the signal ~. Just like the coffee I tried to add. 
Otherwise it's perfect! 💪

**Comment by florianblaschke** [comment]
Hi Miguel! This is intended...that Coffee is part of the Original Database and should persist as it is 🗡️ The Edit functionality will be gone with my next US

**Comment by migueljcpinto** [comment]
But if you want to add new foreign coffee with strange signs, you will have the same problem.Like my coffee "Príncipe", from São Tomé e Príncipe 😭😭

**Comment by florianblaschke** [comment]
Then I will change my RegEx accordingly – for you ❤️
