### ISSUE TITLE
US 8 Edit Brew Recipes

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#15]
## Value Proposition

As a Beanerd I want to be able to Edit my Brew Recipes 
​

## Description

The Edit Function for the coffee will have to go since the data should be inserted by the Roasters themselves. 

![Image](https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/a85c3715-bf91-4f80-9c9e-5a57afe2b359)

​

## Acceptance Criteria

- [x] I can edit my Brew recipes in my Login
- [x] The Edit-Form will be showed in a Modal
- [x] I can not edit an existing coffee anymore
      ​

## Tasks

- [x] create a Modal
- [x] inside the Modal will be the form to Edit the picked recipe
- [x] handle Logic for API
- [x] delete Logic for Editing a Coffee
      ​

## Complexity

M
