### ISSUE TITLE
US9 Login Status and Favorite

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#17]
## Value Proposition

As a User I want to see on every page wether I am logged in or not. Also if I inspect a Roast, I want to see if it is already in my Favorites.
​

## Description

![Image](https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/24e469d4-42f7-4a3d-9ee7-ad0b277feeab)
<img width="261" alt="Bildschirmfoto 2023-08-24 um 12 57 26" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/dabd4285-b161-46dc-bcba-8d6e05b11335">

​

## Acceptance Criteria

- [x] I can see if I am logged in and can log-out from every page
- [x] I can see if a Roast is already in my favorites if I inspect it
      ​

## Tasks

- [x] update my Layout with the login status at the top
- [x] make the favorite-button toggle it's value depending if a roast is already favorite or not
      ​

## Complexity

XS

**Comment by DorisW3** [comment]
Hi Florian,

why don't you display the favorite button on the page shown in the wireframe? It could be annoying for the user to just clicking on roast to see whether it is a favorite or not. However, you should show the "inspect" page as a wireframe to display the favorite button.

**Comment by florianblaschke** [comment]
Yeah. Maybe I could do that aswell. The detail Page was part of another US, so I did not include it because of just one tiny little text change on a button. Maybe you could give me a greenlight although this is missing? ;)

**Comment by JanaS87** [comment]
Hey,
app looks great, and everything works well 👍 
I have a question about the favorite-mark. Is it correct, that it's displayed on the left side, below the card I liked? If it's my browser, then everything's fine :) If not, that could be a little bit confusing. 

See here:
![favorite-roast](https://github.com/florianblaschke/capstone-project-beanerd/assets/136725332/13b9d3e1-6b66-4cbf-a93f-fcdcf412e5ae)

Nice work so far, keep going 👍
