### ISSUE TITLE
US10 Deleting a Brew Recipe

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#19]
## Value Proposition

As a User I want to be able to delete one or more of the brew recipes I created.
​

## Description

![Image](https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/968652ec-9b6d-4714-9e41-a2f737b52d8a)

​

## Acceptance Criteria

- [x] I can delete a Brew Recipe
      ​

## Tasks

- [x] write logic for API and ClientSide
- [x] implement a delete button
      ​

## Complexity

M
