### ISSUE TITLE
US 2

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#2]
## US 2 Adding a new Coffee

As a Beanerd
I want to be able, to save a new Coffee if it is not present yet.

​

## Description

Right now you are just seeing different coffees. With this form, you will be able to submit a new coffee.

<img width="359" alt="Bildschirmfoto 2023-07-31 um 11 12 43" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/2c268d6e-a11c-4f8a-b16d-e2289dfd83c4">

​

## Acceptance Criteria

- [x] I can navigate to the Form for adding a new Coffee
- [x] I can add a new Coffee 
- [x] It gets displayed on the main page

## Tasks

- [x] Create a NavigationBar
- [x] Create a Form for adding a new roast
- [x] Write Tests for the Form
- [x] Store the new Roast in MongoDB
- [x] Write function for Create
      ​

## Complexity

XS

**Comment by tejue** [comment]
Hey Florian, 

I suggest you stick to the formal way of writing US

Title: Something more descriptive than just US would be nice, like: Add a new coffee

Value Proposition (also title is missing :slightly_smiling_face: ), which is: As a ... I want to ... So that I... 
So in your case that would be something like: 

As a Beanerd
I want to be able to save a new Coffee 
So that I can add my favorite one, if its not in the list already.

Acceptance criteria:
It's a bit too short in my opinion. Maybe it helps to think about would will be checked when someone is doing the QA. Something like.
A button to create a new entry is visible.
When clicking the button... happens.
etc.

Last thing, but probably the most important one: I think you are trying to put three US's into one. Coaches told us: the moment you want to use the word "and" it is probably more than just one US :slightly_smiling_face:

**Comment by Roland-Hufnagel** [comment]
Hi Florian. Good Userstory (even if I don't think it's XS). But some things are not clear to me, when I read it:
- What is that image in the description? Do you have an image-upload? Please mention that in the acceptance-criteria and tasks or remove it from the wireframe.
- I see a slider in the wireframe and have no idea, what it is for.
- You write about a navigation bar but I can't find it in the wireframe.

Can you please adapt your US to make things clearer for the one that reads it. Thanks!

**Comment by florianblaschke** [comment]
Hi!

Image Upload is intended but I wanted to do it at a later stage. So I thought, I might just leave it there, since all the Coffees are getting display with a default picture.
The slider is for adjusting the Arabica / Robusta Ratio.

Updated the Image with Navigationbar

**Comment by Roland-Hufnagel** [comment]
Ah okay. Now it looks clear to me 💪
