### ISSUE TITLE
US 11

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#21]
## Value Proposition

As a User I want to have a better overview at the start page. I want to have different sections which are leading me fast to the coffee I want to see.
​

## Description

![Image](https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/f3e06770-14ba-4e31-bd34-7ce8dd5554ab)

​
## Acceptance Criteria

- [x] there are different filter methods which are linked to the category
- [x] You can scroll to the different sections
​

## Tasks

- [x] Filter roasts and display them in the correct section
- [x] Create the links to the sections
      ​

## Complexity

M
