### ISSUE TITLE
US12 Search

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#23]
## Value Proposition

As a Beanerd I want to be able to search for different roasts via the arabica/robusta-ratio, name or the roaster.
​

## Description

<img width="315" alt="Bildschirmfoto 2023-09-06 um 10 26 17" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/28ca555e-2137-4f11-b351-a5d3d91d21aa">
​

## Acceptance Criteria

- [x] implement a search bar on a new page called "search"
- [x] I can search for the name, roaster or ratio
      ​

## Tasks

- [x] create new page
- [x] create search algorhythm
- [x] show the searched items on the page
      ​

## Complexity

L

**Comment by donacrisante** [comment]
Nice!
