### ISSUE TITLE
US 3

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#3]
## US 3

As a Beanerd I want to be able to delete or edit one of the roasts, in case I did something wrong when I created it.
​

## Description

With this Update you will be able to Edit and Delete a Roast.

<img width="411" alt="Bildschirmfoto 2023-08-02 um 09 32 00" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/9fb5cd2d-38c4-498a-8074-d9e5f4dcaa03">

​

## Acceptance Criteria

- [x] Adding an Edit Button which makes the roast editable
- [x] I can then save changes or delete the whole roast
      ​

## Tasks

- [x] Create a Edit Button
- [x] Make a Form for Editing the roast
- [x] Write the logic in the API
- [x] Write the logic on the DetailPage
      ​

## Complexity

S
