### ISSUE TITLE
US 4 NextAuth

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#7]
## Making Beanerd a community app (step 1)

As a Beanerd I want to be able to create my own account, in which I can then store my favourite roasts and Brew Methods and Settings.
​

## Description

Beanerd will be an App with a community which shares passion for Specialty Coffee and different Brewing Methods. A Rating System will be introduced in upcoming US, as well as the option to save Brew Settings for a roast in your favorites collection.

Also in the future you will be able to delete roasts out of your favorite Collection but not out of the general database (like it is now).

![Image](https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/9e6e0a99-c6c0-4ae4-8995-d90a22836cd1)

## Acceptance Criteria

- [x] I can navigate to the profile page
- [x] I can create an account
- [x] I can log into my account
- [x] I can save a roast in my favorites collection
      ​

## Tasks

- [x] Create Profile Page
- [x] Implement nextAuth Credentials Provider
- [x] Write API with logic for account creation
- [x] write logic on Profile Page for account creation
- [x] Add Favorites Button to RoastDetailCard
- [x] Clicking the Button will add the roast to my favourites
      ​

## Complexity

M
