### ISSUE TITLE
US 5

### ISSUE THREAD

**Issue by florianblaschke** [florianblaschke/capstone-project-beanerd#9]
## Value Proposition

As a member of Beanerd I want to be able to delete a Roast out of my Collection Tab.

## Description

Since Beanerd is now a multi-user app, you won't be able to delete a roast out of the database. So the DELETE Button in the DetailView will disappear. You will be able to delete a Roast out of your Collection Tab in your profile.
​
<img width="436" alt="Bildschirmfoto 2023-08-08 um 12 25 22" src="https://github.com/florianblaschke/capstone-project-beanerd/assets/127996345/58c17cc0-1fae-479c-ad42-4c3d9875a51d">

## Acceptance Criteria

- [x] I am not able to delete a roast out of database
- [x] I am able to delete a roast out of my collection in my Profile
      ​

## Tasks

- [x] get rid of the delete Button in DetailView
- [x] delete the logic for deleting a Roast
- [x] implement a Delete Button in Profile Tab
- [x] create logic for deleting a Roast out of collection in Profile Tab
      ​

## Complexity

XS
